AppBundle\Entity\City:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 32
      nullable: false
    lng:
      type: string
      length: 50
      nullable: false
    ltd:
      type: string
      length: 32
      nullable: false
  oneToMany:
    statuses:
      targetEntity: Status
      mappedBy: id