AppBundle\Entity\Status:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    note:
      type: string
      length: 32
      nullable: false
    lng:
      type: string
      length: 50
      nullable: false
    ltd:
      type: string
      length: 32
      nullable: false
    date:
      type: datetime
      nullable: false
  manyToOne:
    city:
      targetEntity: City
      joinColumn:
        name: city_id
        referencedColumnName: id
      inversedBy: statuses
    user:
      targetEntity: User
      joinColumn:
        name: user_id
        referencedColumnName: id
      inversedBy: statuses
